### ISSUE TITLE
java.lang.NoSuchMethodError on BuildInfo.apply

### ISSUE THREAD

**Issue by dguo-coursera** [sbt/sbt-buildinfo#107]
Encountered this error on compile:buildInfo after migrating from 0.3.1 to 0.7.0. Have tried `sbt clean` and deleting artifacts from coursier & ivy2.

SBT version: 0.13.13
Scala version: 2.11.8

```
java.lang.NoSuchMethodError: sbtbuildinfo.BuildInfo$.apply(Ljava/io/File;Lsbtbuildinfo/BuildInfoRenderer;Ljava/lang/String;Lscala/collection/Seq;Lscala/collection/Seq;Lsbt/ProjectRef;Lsbt/State;Ljava/io/File;)Ljava/io/File;
	at sbtbuildinfo.BuildInfoPlugin$$anonfun$buildInfoScopedSettings$1.apply(BuildInfoPlugin.scala:46)
	at sbtbuildinfo.BuildInfoPlugin$$anonfun$buildInfoScopedSettings$1.apply(BuildInfoPlugin.scala:46)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
